# Running company -> (country, confidence) lookup for LinkedIn refreshes.
# Campaign Manager's company export doesn't report country, so this is built up
# manually across refresh sessions instead of re-researched each time.
# confidence: H = confident, M = best-effort (worth a sanity check if it matters for a decision)
CLASSIFY = {
    "Capgemini": ("France", "H"),
    "Emirates NBD": ("UAE", "H"),
    "Tata Consultancy Services": ("UK", "H"),
    "Amazon Web Services (AWS)": ("Ireland", "H"),
    "Siemens": ("Germany", "H"),
    "AUMOVIO": ("Europe", "H"),
    "Nokia": ("Finland", "H"),
    "Vodafone": ("UK", "H"),
    "Deutsche Bank": ("Germany", "H"),
    "IBM": ("UK", "H"),
    "SAP": ("Germany", "H"),
    "Cognizant": ("UK", "H"),
    "Ericsson": ("Sweden", "H"),
    "Akbank": ("Turkey", "H"),
    "LSEG": ("UK", "H"),
    "ING Türkiye": ("Turkey", "H"),
    "Rabobank": ("Netherlands", "H"),
    "VakıfBank": ("Turkey", "H"),
    "Sky": ("UK", "H"),
    "Bosch": ("Germany", "H"),
    "ASML": ("Netherlands", "H"),
    "Halkbank": ("Turkey", "H"),
    "Arm": ("UK", "H"),
    "CrowdStrike": ("UK", "M"),
    "Wolt": ("Finland", "H"),
    "Delivery Hero": ("Germany", "H"),
    "NXP Semiconductors": ("Netherlands", "H"),
    "Valeo": ("France", "H"),
    "IKEA": ("Sweden", "H"),
    "Lloyds Banking Group": ("UK", "H"),
    "Revolut": ("UK", "H"),
    "Eaton": ("Ireland", "H"),
    "Continental": ("Germany", "H"),
    "Booking.com": ("Netherlands", "H"),
    "ING Nederland": ("Netherlands", "H"),
    "First Abu Dhabi Bank (FAB)": ("UAE", "H"),
    "Cisco": ("Netherlands", "M"),
    "Infineon Technologies": ("Germany", "H"),
    "Volvo Cars": ("Sweden", "H"),
    "Sage": ("UK", "H"),
    "UBS": ("Switzerland", "H"),
    "Visa": ("UK", "M"),
    "Roche": ("Switzerland", "H"),
    "Philips": ("Netherlands", "H"),
    "A.P. Moller - Maersk": ("Denmark", "H"),
    "Spotify": ("Sweden", "H"),
    "Zalando": ("Germany", "H"),
    "ING": ("Netherlands", "H"),
    "BASF": ("Germany", "H"),
    "Turkish Airlines": ("Turkey", "H"),
    "ABN AMRO Bank N.V.": ("Netherlands", "H"),
    "Allianz Technology": ("Germany", "H"),
    "Qatar Airways": ("Qatar", "H"),
    "KPN": ("Netherlands", "H"),
    "Mercedes-Benz AG": ("Germany", "H"),
    "TomTom": ("Netherlands", "H"),
    "Klarna": ("Sweden", "H"),
    "Just Eat Takeaway.com": ("Netherlands", "H"),
    "Novo Nordisk": ("Denmark", "H"),
    "SEB": ("Sweden", "H"),
    "Nordea": ("Denmark", "H"),
    "SIX": ("Switzerland", "H"),
    "OP Pohjola": ("Finland", "H"),
    "Nationale-Nederlanden": ("Netherlands", "H"),
    "Volvo Group": ("Sweden", "H"),
    "Zurich Insurance": ("Switzerland", "H"),
    "Zürcher Kantonalbank": ("Switzerland", "H"),
    "DNB": ("Norway", "H"),
    "ADIB - Abu Dhabi Islamic Bank": ("UAE", "H"),
    "King": ("UK", "H"),
    "VECTOR Informatik": ("Germany", "H"),
    "Scania Group": ("Sweden", "H"),
    "Worldpay": ("UK", "H"),
    "Roads and Transport Authority": ("UAE", "H"),
    "Danske Bank": ("Denmark", "H"),
    "NN": ("Netherlands", "H"),
    "Wolters Kluwer": ("Netherlands", "H"),
    "Santander UK": ("UK", "H"),
    "Adyen": ("Netherlands", "H"),
    "PostNL": ("Netherlands", "H"),
    "Finastra": ("UK", "H"),
    "BMW Group": ("Germany", "H"),
    "Zendesk": ("Ireland", "M"),
    "Ayesa": ("Spain", "H"),
    "Elsevier": ("Netherlands", "H"),
    "KLM Royal Dutch Airlines": ("Netherlands", "H"),
    "Barclays": ("UK", "H"),
    "Stellantis": ("Netherlands", "M"),
    "Clarivate": ("UK", "M"),
    "Kuehne+Nagel": ("Switzerland", "H"),
    "GSK": ("UK", "H"),
    "Erste Digital": ("Austria", "H"),
    "Entain": ("UK", "H"),
    "Novartis": ("Switzerland", "H"),
    "HCLTech": ("UK", "M"),
    "Deutsche Telekom": ("Germany", "H"),
    "Lonza": ("Switzerland", "H"),
    "du": ("UAE", "H"),
    "Synamedia": ("UK", "H"),
    "Aptiv": ("Ireland", "M"),
    "American Express": ("UK", "M"),
    "Philip Morris International": ("Switzerland", "M"),
    "BT Group": ("UK", "H"),
    "DWP Digital": ("UK", "H"),
    "Direct Line Group": ("UK", "H"),
    "AstraZeneca": ("UK", "H"),
    "Mashreq": ("UAE", "H"),
    "Toyota Motor Europe": ("Belgium", "H"),
    "Aon": ("Ireland", "M"),
    "Nationwide Building Society": ("UK", "H"),
    "Backbase": ("Netherlands", "H"),
    "Euroclear": ("Belgium", "H"),
    "STMicroelectronics": ("Switzerland", "H"),
    "Groupe BPCE": ("France", "H"),
    "Deliveroo": ("UK", "H"),
    "DSV - Global Transport and Logistics": ("Denmark", "H"),
    "If Insurance": ("Sweden", "M"),
    "Standard Chartered": ("UK", "H"),
    "bp": ("UK", "H"),
    "HUGO BOSS": ("Germany", "H"),
    "Commercial Bank of Dubai": ("UAE", "H"),
    "Legal & General": ("UK", "H"),
    "Sandoz": ("Switzerland", "H"),
    "Aviva": ("UK", "H"),
    "Bosch Engineering GmbH": ("Germany", "H"),
    "SumUp": ("UK", "M"),
    "Wise": ("UK", "H"),
    "Next": ("UK", "H"),
    "Checkout.com": ("UK", "H"),
    "stc": ("Saudi Arabia", "H"),
    "Bank of Ireland": ("Ireland", "H"),
    "Shell": ("Netherlands", "H"),
    "Merck Group": ("Germany", "H"),
    "Swedbank": ("Sweden", "H"),
    "WTW": ("UK", "M"),
    "AUDI AG": ("Germany", "H"),
    "Swiss Re": ("Switzerland", "H"),
    "British Airways": ("UK", "H"),
    "Sogeti": ("France", "H"),
    "Handelsbanken": ("Sweden", "H"),
    "People's Partnership": ("UK", "H"),
    "Ingenico": ("France", "H"),
    "Dentsply Sirona": ("Germany", "M"),
    "DenizBank": ("Turkey", "H"),
    "LTIMindtree": ("UK", "M"),
    "AIB": ("Ireland", "H"),
    "Sainsbury's": ("UK", "H"),
    "Sopra Steria": ("France", "H"),
    "Accenture": ("Ireland", "H"),
    "FNZ": ("UK", "M"),
    "Bank of England": ("UK", "H"),
    "Playtech": ("UK", "M"),
    "Financial Conduct Authority": ("UK", "H"),
    "SailPoint": ("UK", "M"),
    "Nagarro": ("Germany", "H"),
    "Capgemini Engineering": ("France", "H"),
    "HUK-COBURG": ("Germany", "H"),
    "Julius Baer": ("Switzerland", "H"),
    "Tesco": ("UK", "H"),
    "Tech Mahindra": ("UK", "M"),
    "NTT DATA Business Solutions": ("Germany", "M"),
    "ProRail": ("Netherlands", "H"),
    "Selfridges": ("UK", "H"),
    "Deutsche Börse Group": ("Germany", "H"),
    "talabat": ("UAE", "M"),
    "Tele2": ("Sweden", "H"),
    "Barclays Investment Bank": ("UK", "H"),
    "Hogarth": ("UK", "M"),
    "Mobica": ("UK", "M"),
    "Nordic Semiconductor": ("Norway", "H"),
    "Capco": ("UK", "H"),
    "Emirates": ("UAE", "H"),
    "Hepsiburada (NASDAQ: HEPS)": ("Turkey", "H"),
    "ION": ("Ireland", "M"),
    "Temenos": ("Switzerland", "H"),
    "SAP Ariba": ("Germany", "H"),
    "Credit Suisse": ("Switzerland", "H"),
    "Randstad": ("Netherlands", "H"),
    "Wipro": ("UK", "M"),
    "Infosys": ("UK", "M"),
    "DXC Technology": ("UK", "M"),
    "Signify": ("Netherlands", "H"),
    "Luxoft": ("Switzerland", "M"),
    "Monzo": ("UK", "H"),
    "aramco": ("Saudi Arabia", "H"),
    "FINEOS": ("Ireland", "H"),
    "Algihaz Holding": ("Saudi Arabia", "H"),
    "Qualitest": ("Israel", "H"),
    "Technology Innovation Institute": ("UAE", "H"),
    "BBC": ("UK", "H"),
    "Boehringer Ingelheim": ("Germany", "H"),
    "John Lewis Partnership": ("UK", "H"),
    "Ampere Software Technology": ("France", "M"),
    "Sandvik": ("Sweden", "H"),
    "Schneider Electric": ("France", "H"),
    "CEGEDIM": ("France", "H"),
    "Majid Al Futtaim": ("UAE", "H"),
    "Nestlé": ("Switzerland", "H"),
    "Takamol Holding": ("Saudi Arabia", "H"),
    "Hitachi Rail": ("UK", "M"),
    "Wix": ("Israel", "H"),
    "Elbit Systems Israel": ("Israel", "H"),
    "JetBrains": ("Czech Republic", "M"),
    "Mimecast": ("UK", "M"),
    "Raiffeisen Bank Russia": ("Russia", "H"),
    "monday.com": ("Israel", "H"),
    "TÜV Rheinland Middle East": ("UAE", "M"),
    "EJADA": ("Saudi Arabia", "H"),
    "Tamkeen Technologies": ("Saudi Arabia", "H"),
    "Fidelity Investments": ("Ireland", "H"),
    "OpenBet": ("UK", "M"),
    "Network International": ("UAE", "H"),
    "Expleo Group": ("France", "H"),
    "Elm Company": ("Saudi Arabia", "H"),
    "Careem": ("UAE", "H"),
    "Telenor": ("Norway", "H"),
    "Betfred": ("UK", "M"),
    "SSE plc": ("UK", "H"),
    "Thales": ("France", "H"),
    "Indra Group": ("Spain", "H"),
    "hiberus": ("Spain", "H"),
    "Swisscom": ("Switzerland", "H"),
    "ALTEN": ("France", "H"),
    "Airbus": ("France", "M"),
    "Inetum": ("France", "H"),
    "Saab": ("Sweden", "H"),
    "Amadeus": ("Spain", "H"),
    "Worldline": ("France", "H"),
    "knowmad mood": ("Spain", "M"),
    "Mobileye": ("Israel", "H"),
    "Atos": ("France", "H"),
    "Axis Communications": ("Sweden", "H"),
    "Astek": ("France", "H"),
    "Dassault Systèmes": ("France", "H"),
    "Sngular": ("Spain", "H"),
    "CARIAD": ("Germany", "H"),
    "MBition": ("Germany", "H"),
    "Belastingdienst": ("Netherlands", "H"),
    "ALTEN Spain": ("Spain", "H"),
    "Sportradar": ("Switzerland", "H"),
    "Minsait": ("Spain", "H"),
    "Google DeepMind": ("UK", "H"),
    "TUI": ("Germany", "H"),
    "Siemens Healthineers": ("Germany", "H"),
    "CaixaBank Tech": ("Spain", "H"),
    "IHG Hotels & Resorts": ("UK", "H"),
    "Rafael Advanced Defense Systems": ("Israel", "H"),
    "Version 1": ("Ireland", "H"),
    "Plexus Tech": ("Spain", "M"),
    "Netcompany": ("Denmark", "H"),
    "Accor": ("France", "H"),
    "Société Générale": ("France", "H"),
    "SociÃ©tÃ© GÃ©nÃ©rale": ("France", "H"),  # mojibake alias seen in one export
    "SEIDOR": ("Spain", "H"),
    "noon": ("UAE", "H"),
    "Enedis": ("France", "H"),
    "DP World": ("UAE", "H"),
    "GFT Technologies": ("Germany", "H"),
    "Cegid": ("France", "H"),
    "Ciklum": ("UK", "M"),
    "Telefónica": ("Spain", "H"),
    "Knowit": ("Sweden", "H"),
    "Cognyte": ("Israel", "H"),
    "AXA": ("France", "H"),
    "Orange Business": ("France", "H"),
    "TeamViewer": ("Germany", "H"),
    "Mercedes-Benz Tech Innovation": ("Germany", "H"),
    "Telia": ("Sweden", "H"),
    "ASOS.com": ("UK", "H"),
    "Keywords Studios": ("Ireland", "H"),
    "The Access Group": ("UK", "H"),
    "Pearson": ("UK", "H"),
    "Systematic": ("Denmark", "H"),
    "Konecranes": ("Finland", "H"),
    "B. Braun Group": ("Germany", "H"),
    "SEPHORA": ("France", "H"),
    "Grifols": ("Spain", "H"),
    "dormakaba": ("Switzerland", "H"),
    "dSPACE": ("Germany", "H"),
    "Fiverr": ("Israel", "H"),
    "BBC Studios": ("UK", "H"),
    "IG Group": ("UK", "H"),
    "SITA": ("Switzerland", "H"),
    "Devoteam": ("France", "H"),
    "Giesecke+Devrient": ("Germany", "H"),
    "Capita": ("UK", "H"),
    "London Stock Exchange": ("UK", "H"),
    "HSBC": ("UK", "H"),
}

# excluded: no clear enterprise ICP fit, no identifiable/EMEA entity, or signal too weak to matter
EXCLUDED = {
    "Vitelco", "ID3", "TrustMotion", "TikTok", "YouTube", "DoorDash",
    "Microsoft", "EY", "Deloitte",  # noise-level raw signal (views=3)
    "Renesas Electronics", "Technical University of Munich", "Virtusa",
    "Island", "The University of Edinburgh", "EPAM Systems", "GE Aerospace",
    "ValueLabs", "Synechron", "pulse by solutions", "Larsen & Toubro",
    "Tata Projects", "Hummingbird Digital Design", "Confidential Government",
    "Stealth Startup", "LeadDev", "Washington Components", "Matrix",
    "Comcast", "HealthforAnimals",
    "Kacha | ᱠᱟ", "Speridian Technologies",
    "Universitat de Vic – Universitat Central de Catalunya (UVic-UCC)",
    "Ubimax", "KPMG US", "HSLU Hochschule Luzern",
}

NORTH_CORE = {"UK", "Germany", "Netherlands", "Sweden", "Switzerland", "Ireland", "Norway",
    "Denmark", "Belgium", "Luxembourg", "Lithuania", "Finland", "Russia", "Russian Federation",
    "Austria", "Poland", "Czech Republic", "Hungary", "Romania", "Slovakia", "Bulgaria", "Greece",
    "Latvia", "Estonia", "Europe"}
SOUTH_CORE = {"France", "UAE", "Saudi Arabia", "Israel", "Spain", "Italy", "Turkey", "Türkiye",
    "Croatia", "Portugal", "Egypt", "Morocco", "Qatar", "Bahrain", "Kuwait", "Jordan", "Cyprus",
    "Lebanon", "Tunisia", "Algeria"}
